#ifndef ROS_IMPEDANCE_CONTROLLER_HPP
#define ROS_IMPEDANCE_CONTROLLER_HPP

// ROS2
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include <sensor_msgs/msg/joint_state.hpp>

// custom messages & services (generated by rosidl)
#include <ros_impedance_controller/msg/effort_pid.hpp>
#include <ros_impedance_controller/msg/pid.hpp>
#include <ros_impedance_controller/srv/set_pids.hpp>

// ros2_control
#include <controller_interface/controller_interface.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/loaned_state_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>

// realtime tools
#include <realtime_tools/realtime_buffer.hpp>
#include <realtime_tools/realtime_publisher.hpp>

// Eigen
#include <Eigen/Dense>

#include <memory>
#include <string>
#include <vector>

namespace ros_impedance_controller
{

/**
 * @brief ros2_control implementation of the ROS impedance (PID + feed-forward)
 * controller. It claims one effort command interface and position/velocity
 * state interfaces per joint. The control math is identical to the original
 * ROS1 ros_control plugin.
 */
class Controller : public controller_interface::ControllerInterface
{
public:
    Controller();
    ~Controller() override;

    /** @brief Declare parameters used by the controller. */
    controller_interface::CallbackReturn on_init() override;

    /** @brief Read parameters (joints, gains, home, joint_type). */
    controller_interface::CallbackReturn on_configure(
        const rclcpp_lifecycle::State & previous_state) override;

    /** @brief Assign loaned interfaces and reset state. */
    controller_interface::CallbackReturn on_activate(
        const rclcpp_lifecycle::State & previous_state) override;

    /** @brief Release interfaces. */
    controller_interface::CallbackReturn on_deactivate(
        const rclcpp_lifecycle::State & previous_state) override;

    /** @brief Which command interfaces the controller claims. */
    controller_interface::InterfaceConfiguration command_interface_configuration() const override;

    /** @brief Which state interfaces the controller claims. */
    controller_interface::InterfaceConfiguration state_interface_configuration() const override;

    /** @brief Real-time control loop. */
    controller_interface::return_type update(
        const rclcpp::Time & time, const rclcpp::Duration & period) override;

private:
    // Command message shared with the real-time update() through a buffer
    struct Command
    {
        Eigen::VectorXd des_joint_positions;
        Eigen::VectorXd des_joint_velocities;
        Eigen::VectorXd des_joint_efforts;
    };

    void commandCallback(const sensor_msgs::msg::JointState::SharedPtr msg);
    void setPidsCallback(
        const std::shared_ptr<ros_impedance_controller::srv::SetPids::Request> req,
        std::shared_ptr<ros_impedance_controller::srv::SetPids::Response> res);

    // ROS2 interfaces
    rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr command_sub_;
    rclcpp::Service<ros_impedance_controller::srv::SetPids>::SharedPtr set_pids_srv_;
    std::shared_ptr<realtime_tools::RealtimePublisher<ros_impedance_controller::msg::EffortPid>> effort_pid_pub_;
    rclcpp::Publisher<ros_impedance_controller::msg::EffortPid>::SharedPtr effort_pid_pub_raw_;

    realtime_tools::RealtimeBuffer<Command> command_buffer_;

    /** @brief Joint names */
    std::vector<std::string> joint_names_;
    std::vector<std::string> joint_type_;

    /** @brief Desired joint efforts */
    Eigen::VectorXd des_joint_efforts_;
    /** @brief Desired joint positions */
    Eigen::VectorXd des_joint_positions_;
    /** @brief Old integral action */
    Eigen::VectorXd integral_action_old_;
    /** @brief Desired joint velocities */
    Eigen::VectorXd des_joint_velocities_;
    Eigen::VectorXd proportional_action_;
    Eigen::VectorXd integral_action_;
    Eigen::VectorXd derivative_action_;

    /** @brief PID gains */
    std::vector<double> joint_p_gain_;
    std::vector<double> joint_i_gain_;
    std::vector<double> joint_d_gain_;

    Eigen::VectorXd measured_joint_position_;
    Eigen::VectorXd measured_joint_velocity_;
    Eigen::VectorXd joint_positions_old_;
    Eigen::VectorXd des_joint_efforts_pids_;

    // Discrete implementation variables
    Eigen::VectorXd error_;
    Eigen::VectorXd error1_;
    Eigen::VectorXd T_d, T_i;
    Eigen::VectorXd use_integral_action_;
    const int N = 8;
    double Ts = 0.;

    std::string robot_name_;
    bool verbose_ = false;
    bool discrete_implementation_ = false;
};

} // namespace ros_impedance_controller

#endif // ROS_IMPEDANCE_CONTROLLER_HPP
