#!/usr/bin/env python3
"""ROS2 port of go2_description/launch/upload.launch.

Runs xacro on the Go2 URDF and publishes it on the `robot_description`
parameter of the robot_state_publisher node. The SRDF is exposed on the
`robot_semantic_description` parameter (kept for parity with ROS1).

Implementation note
-------------------
We process the xacro files with the ``xacro`` *Python API* inside an
``OpaqueFunction`` instead of using ``Command([FindExecutable('xacro'), ...])``.

Reason: when the ``xacro`` executable is not on the PATH, ROS2's
``FindExecutable`` raises a *misleading* error that prints the repr of its
internal substitution list, e.g.::

    executable '[<launch.substitutions.text_substitution.TextSubstitution
    object at 0x...>]' not found on the PATH

Using the Python API resolves the URDF at launch time and, if xacro is
genuinely missing, fails with a clear ``ModuleNotFoundError: No module named
'xacro'`` telling the user to install ``ros-humble-xacro``.
"""

import os
import re

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

import xacro


def _strip_xml_comments(xml):
    """Remove all XML comments (<!-- ... -->) from a URDF/SRDF string.

    Why this is required
    --------------------
    The gazebo_ros2_control plugin (Humble) reads this URDF back from the
    robot_state_publisher `robot_description` parameter and re-injects it into
    the embedded controller_manager as a command-line parameter override rule
    (``--param robot_description:=<urdf>``). rcl's argument parser then chokes
    on special characters (``:``, ``#``, decorative sequences) that appear
    inside XML comments, aborting with:

        parser error Couldn't parse parameter override rule:
        '--param robot_description:=<?xml ...'

    When the plugin aborts, the controller_manager never starts and the
    joint_state_broadcaster / ros_impedance_controller spawners time out with
    'Could not contact service /controller_manager/list_controllers'.

    Comments are non-semantic in URDF/SRDF, so stripping them is safe and
    guarantees no comment-borne character can break the parser (this includes
    the autogenerated xacro header comment). XML forbids ``--`` inside a
    comment, so the non-greedy DOTALL regex below is unambiguous.
    """
    return re.sub(r'<!--.*?-->', '', xml, flags=re.DOTALL)


def _spawn_state_publisher(context, *args, **kwargs):
    """Resolve LaunchConfigurations, run xacro, and build robot_state_publisher."""
    pkg = get_package_share_directory('go2_description')

    task_period = LaunchConfiguration('task_period').perform(context)
    load_force_sensors = LaunchConfiguration('load_force_sensors').perform(context)

    urdf_xacro = os.path.join(pkg, 'robots', 'go2.urdf.xacro')
    srdf_xacro = os.path.join(pkg, 'robots', 'go2.srdf.xacro')

    robot_description = _strip_xml_comments(xacro.process_file(
        urdf_xacro,
        mappings={
            'task_period': task_period,
            'load_force_sensors': load_force_sensors,
        },
    ).toxml())

    # SRDF is optional; keep launch working even if it fails to process.
    try:
        robot_semantic = _strip_xml_comments(xacro.process_file(srdf_xacro).toxml())
    except Exception:  # noqa: BLE001 - SRDF is non-critical for simulation
        robot_semantic = ''

    return [
        Node(
            package='robot_state_publisher',
            executable='robot_state_publisher',
            name='robot_state_publisher',
            output='screen',
            parameters=[{
                'robot_description': robot_description,
                'robot_semantic_description': robot_semantic,
                'use_sim_time': True,
            }],
        ),
    ]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('robot_name', default_value='go2'),
        DeclareLaunchArgument('sensors', default_value='true'),
        DeclareLaunchArgument('task_period', default_value='0.001'),
        DeclareLaunchArgument('load_force_sensors', default_value='false'),

        OpaqueFunction(function=_spawn_state_publisher),
    ])
